services:
  - type: web
    name: streamcarnia-api
    runtime: docker
    dockerfilePath: ./Dockerfile
    healthCheckPath: /api/health
    envVars:
      - key: CORS_ORIGINS
        sync: false
      - key: YOUTUBE_COOKIES_FILE
        sync: false
      - key: STAGING_DIR
        value: /tmp/StreamCarnia
      - key: APPWRITE_ENDPOINT
        value: https://cloud.appwrite.io/v1
      - key: APPWRITE_PROJECT_ID
        sync: false
      - key: GITHUB_OWNER
        sync: false
      - key: GITHUB_REPOSITORY
        sync: false
      - key: GITHUB_TOKEN
        sync: false
      - key: GITHUB_TARGET_BRANCH
        value: main
        sync: false